/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActiveTableInfo: typeof import('./src/components/ActiveTableInfo.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    CustomConnectionLine: typeof import('./src/components/ERD/CustomConnectionLine.vue')['default']
    CustomEdge: typeof import('./src/components/ERD/CustomEdge.vue')['default']
    DbGroup: typeof import('./src/components/ERD/DbGroup.vue')['default']
    DbTable: typeof import('./src/components/ERD/DbTable.vue')['default']
    EditorPage: typeof import('./src/components/page/EditorPage.vue')['default']
    Flow: typeof import('./src/components/ERD/Flow.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProjectInfo: typeof import('./src/components/ProjectInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Settings.vue')['default']
    TablesList: typeof import('./src/components/TablesList.vue')['default']
    TagsTableList: typeof import('./src/components/TagsTableList.vue')['default']
    ViewPage: typeof import('./src/components/page/ViewPage.vue')['default']
  }
}
